### ISSUE TITLE
tracking: Deno streams to web streams conversion

### ISSUE THREAD

**Issue by crowlKats** [denoland/std#1986]
There is also the separate effort to replace any code that uses various deno ns classes that implement `Deno.Reader` & `Deno.Writer` that still uses the `read` & `write` functions over the `readable` & `writable` properties.

### io
- [x] buffer.ts
  - [x] `Buffer` (#1970)
  - [x] `BufReader`: replaced by `ReadableStreamBYOBReader.read(, {atLeast})`
  - [x] `BufWriter`: unnecessary (doesnt make much sense for web streams)
  - [x] `readDelim`: replaced by `streams/delimiter.ts`'s `DelimiterStream`
  - [x] `readStringDelim` (#2006)
  - [x] `readLines`: replaced by `streams/delimiter.ts`'s `TextLineStream`

- [x] files.ts
  - [x] `readRange` replaced by `streams/byte_slice_stream.ts`'s `ByteSliceStream`

- [x] readers.ts
  - [x] `StringReader`: replaced by `TextDecoderStream`
  - [x] `MultiReader`: replaced by `streams/merge.ts`
  - [x] `LimitedReader` (#2007)

- [x] util.ts
  Do we even want these?
  - [x] `copyN`
  - [x] `readShort`
  - [x] `readInt`
  - [x] `readLong`

- [x] writers.ts
  unnecessary.

### archive
- [ ] `tar` (https://github.com/denoland/deno_std/pull/1985)

### encoding
- [x] binary.ts
  - [x] `readExact`: replaced by `ReadableStreamBYOBReader.read(, {atLeast})`
  - [x] `getNBytes`: unecessary
  - [x] `readVarnum`: doesnt this somewhat clash with `io/util.ts` functions?
  - [x] `readVarbig`
  - [x] `writeVarnum`
  - [x]  `writeVarbig`

- [x] csv.ts
  - [x] uses `BufReader` (#1993, #2491)

### log
- [x] handler.ts https://github.com/denoland/deno_std/pull/4021
  - [x] `WriterHandler`
  - [x] `RotatingFileHandler`

### mime
- [x] ~~`multipart`~~ mime was removed in #2336

### textproto
not sure what to do with this one. Update: textproto is removed in #2757

please let me know if I missed any.

**Comment by iuioiua** [comment]
I'll give `readRange` from `files.ts` a crack, if that's still something we want. I'm thinking `RangedTransformStream`.

Also, update:
1. `std/mime` is deprecated
2. `std/textproto` is deprecated
3. Streams-based CSV parsing is implemented

**Comment by iuioiua** [comment]
> ### io
> * [x]  buffer.ts
>   
>   * [x]  `Buffer` ([feat: streams based `Buffer` #1970](https://github.com/denoland/deno_std/pull/1970))
>   * [x]  `BufReader`: replaced by `ReadableStreamBYOBReader.read(, {atLeast})`
>   * [x]  `BufWriter`: unnecessary (doesnt make much sense for web streams)
>   * [x]  `readDelim`: replaced by `streams/delimiter.ts`'s `DelimiterStream`
>   * [x]  `readStringDelim` ([feat(streams): TextDelimiterStream #2006](https://github.com/denoland/deno_std/pull/2006))
>   * [x]  `readLines`: replaced by `streams/delimiter.ts`'s `TextLineStream`

Is the Deno team in favour of deprecating these APIs?

**Comment by lino-levan** [comment]
@crowlKats could you update this issue according to iuioiua's comment?

**Comment by iuioiua** [comment]
CC @crowlKats

**Comment by crowlKats** [comment]
@iuioiua this seems already to have been updated by @kt3k

**Comment by iuioiua** [comment]
> files.ts
> 
> * [ ]  `readRange`

This is done in `streams/ByteSliceStream`.

**Comment by iuioiua** [comment]
Should we aim to have this issue complete by v1?

**Comment by lino-levan** [comment]
That would be nice.

**Comment by iuioiua** [comment]
Update: `copyN()`, `readShort()`, `readInt()` and `readLong()` are deprecated, and can be ticked off. This leaves `std/archive` and `std/log`.

**Comment by kt3k** [comment]
`std/log` has been addressed in https://github.com/denoland/deno_std/pull/4021

**Comment by iuioiua** [comment]
Closing as this work has essentially been completed. The remaining work on `@std/archive` can be tracked in #1658. Thank you to all that helped!
