### ISSUE TITLE
tracking: improve doc checker tools

### ISSUE THREAD

**Issue by iuioiua** [denoland/std#4770]
The [doc checker tool](https://github.com/denoland/deno_std/blob/196101fbeabc3f40f0bc9db6510d9186b1111e6d/_tools/check_docs.ts) should be able to ensure:

- [ ] Exported constants have examples
- [x] Classes have type argument and parameter checks and examples
- [x] Class methods have type argument and parameter checks and examples
- [x] Class properties have examples
- [x] All lint errors are printed together at the end instead of first failure #4834
- [x] #4823
- [x] All optional interface properties have a `@default` tag

**Comment by iuioiua** [comment]
I think the doc checker is fine enough now.
