### ISSUE TITLE
to-do: review custom error classes

### ISSUE THREAD

**Issue by iuioiua** [denoland/std#5476]
The need to ensure any thrown errors are providing value.
- [x] `RetryError`
- [x] `MissingEnvVarsError` (removed in #5450)
- [x] `SubdirectoryMoveError` (removed in #5532)
- [x] `WalkError` (removed in #5477)
- [x] `BufferFullError`
- [x] `PartialReadError`
- [x] `MockError`
- [x] `TimeError` (removed in #5550)

Note: custom error classes from `@std/assert` and `@std/expect` have been omitted on purpose.

**Comment by jsejcksn** [comment]
Unless there's a specific reason to omit the [`options`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Error#options) argument — I think that any [`Error`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error) subclass in `std` (e.g. [`AssertionError`](https://github.com/denoland/std/blob/main/assert/assertion_error.ts), etc.) should also support `options` in its constructor.

There have been many projects I've worked on where I would have loved to use `AssertionError`, but couldn't because it's not currently able to capture a `cause` at construction in order to maintain context during exception-handling.

Similar to:

- https://github.com/denoland/deno/issues/24712

**Comment by iuioiua** [comment]
I'm happy to look at a PR that adds the `options` parameter to `AssertionError`.

**Comment by timreichen** [comment]
Is the error grammar in all std mods the same? I think to remember different ones (`missing xyz: something`, `xyz is missing in something`, `you didn't put xyz in something`). Is this also handled in these PRs?

**Comment by iuioiua** [comment]
Let's look into error messages in a separate issue 🙂
