### ISSUE TITLE
to-do: deprecate and remove `@std/archive`

### ISSUE THREAD

**Issue by iuioiua** [denoland/std#5986]
We now have the streams-based `@std/tar`. In order to deprecate and remove the old `@std/archive`, we must first migrate:

- [x] [jsr:@deno/wasmbuild](https://jsr.io/@deno/wasmbuild)
- [x] [jsr:@libs/bundle](https://jsr.io/@libs/bundle)
- [x] [jsr:@libs/std](https://jsr.io/@libs/std)
- [x] [jsr:@polyseam/inflate-response](https://jsr.io/@polyseam/inflate-response)
